<?php
/**
 * Created by PhpStorm.
 * User: delmwinbaeka
 * Date: 4/14/19
 * Time: 12:32 AM
 */


/**
 * @api {post} /auth/social_register Register(Social)
 * @apiVersion 0.0.1
 * @apiName SocialEmail
 * @apiGroup Auth
 * @apiPermission none
 *
 * @apiDescription Handles registration via social media but requires using the check_user endpoint to first check if
 * user exists with social account already. Returns an encrypted jwt to the client on success of creation. The jwt
 * contains the client apid used to request additional information anytime an api request outside the Auth group is
 * made to the server
 *
 * @apiParam (Social) {String} email User's email address
 * @apiParam (Social) {String} socialToken Social media auth token
 * @apiParam (Social) {String} firebaseToken Firebase token generated by client
 * @apiParam (Social) {String} firstname User's firstname
 * @apiParam (Social) {String} lastname User's lastname
 * @apiParam (Social) {String="facebook", "twitter", "linkedin"} socialType Social media type
 * @apiParam (Social) {String} socialID Unique ID of user with social account
 * @apiParam (Social) {String} phone User's phone number. Format: 233NNNNNNNNN eg. 233501234567
 *
 * @apiParamExample {json} Request-Example (Email):
 *  {
 *      "email": "kofirook@myrookery.com",
 *      "socialToken": "Token here",
 *      "firebaseToken": "firebaseTokenHere",
 *      "firstname": "Kofi",
 *      "lastname": "Rook",
 *      "socialType": "facebook",
 *      "socialID": "Social ID",
 *      "phone": "233501234567"
 *  }
 * *
 * @apiSuccess {Boolean} success=true Shows if request was successful or not
 * @apiSuccess {String} errorMessage Contains the error message generated
 * @apiSuccess {String} errorCode Programmable defined error messages
 * @apiSuccess {Object[]} result List of Request Output for User
 * @apiSuccess {String} result.jwt The JSON Web Token for the user
 * @apiSuccess {Object[]} result.user Contains list of user information
 * @apiSuccess {String} result.user.email Email address of user
 * @apiSuccess {String} result.user.firebaseToken Firebase Token returned to user
 * @apiSuccess {String} result.user.firstname First name of user
 * @apiSuccess {String} result.user.lastname Last name of user
 *
 * @apiSuccessExample {json} Success-Response:
 *  HTTP/1.1 200 OK
 * {
 *      "success": true,
 *      "errorMessage": null,
 *      "errorCode": null,
 *      "result": {
 *                  "jwt": "generated JWT",
 *                  "user": {
 *                              "email": "kofirook@myrookery.com",
 *                              "firstname": "Kofi",
 *                              "lastname": "Rook",
 *                              "firebaseToken": "firebaseTokenHere"
 *                          }
 *                 }
 *  }
 *
 * @apiError {String} USER_CREATION_ERROR User exists or could not be created
 * @apiError {String} MISSING_PARAMETERS Missing one or two parameters in request
 *
 * @apiErrorExample Error-Response (Example):
 *     HTTP/1.1 401 Not Authenticated
 *     {
 *       "success": false,
 *       "errorMessage": "Missing some parameters in request",
 *       "errorCode": "MISSING_PARAMETERS",
 *       "result": null
 *     }
 */

header("Access-Control-Allow-Origin: http://localhost:8080/api/");
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Methods: POST");
header("Access-Control-Max-Age: 3600");
header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");

include_once '../config/database.php';
include_once '../objects/student.php';
include_once '../config/core.php';
include_once '../libs/php-jwt/BeforeValidException.php';
include_once '../libs/php-jwt/ExpiredException.php';
include_once '../libs/php-jwt/SignatureInvalidException.php';
include_once '../libs/php-jwt/JWT.php';
use  \Firebase\JWT\JWT;

$database = new Database();
$db = $database->getConnection();

$student = new Student($db);

$data = json_decode(file_get_contents("php://input"));

if(isset($data->socialID, $data->email, $data->firebaseToken, $data->socialType, $data->phone, $data->firstname, $data->lastname, $data->socialToken)){
    $student->email = $data->email;
    $student->socialID = $data->socialID;
    $student->firebaseToken = $data->firebaseToken;
    $student->firstname = $data->firstname;
    $student->lastname = $data->lastname;
    $student->phone = $data->phone;
    $student->socialToken = $data->socialToken;

    if (isset($data->avatar))
        $student->avatar = $data->avatar;

    if($student->socialCreate($data->socialType)){
        $token = $student->generateJWT();
        $jwt = JWT::encode($token, base64_decode($jwtkey));
        http_response_code(200);
        echo json_encode(
            array(
                "success" => true,
                "errorMessage" => null,
                "errorCode" => null,
                "result" => array(
                    "jwt" => $jwt,
                    "user" => array(
                        "email" => $student->email,
                        "firstname" => $student->firstname,
                        "lastname" => $student->lastname,
                        "firebaseToken" => $student->firebaseToken
                    )
                )
            )
        );
    } else {
        http_response_code(400);
        echo json_encode(
            array(
                "success" => false,
                "errorMessage" => "Could not create user",
                "errorCode" => "USER_CREATION_ERROR",
                "result" => null
            )
        );
    }
} else {
    http_response_code(400);
    echo json_encode(
        array(
            "success" => false,
            "errorMessage" => "Missing one or two parameters in request",
            "errorCode" => "MISSING_PARAMETERS",
            "result" => null
        )
    );
}

?>